### PR TITLE
23 fix inner class may be static inspections

### LINKED ISSUE #23: Fix Inner class may be static inspections
Cleanup lint warnings in function library classes or suppress them as needed.
Verify changes do not cause a regression with Export JAR functions - I'm unsure if there was a gotcha with class path or reflection related to current export jar implementation that relies on inner classes not being static...

### PR DESCRIPTION
**Pull request by NateIsStalling**

### CODE REVIEW

File: library/src/main/java/com/basic4gl/library/standard/TrigBasicLib.java [hunk 1]
```diff
@@ -511,64 +511,64 @@ static boolean ReadMatrix (TomVM vm, int index, float[] m) {
...
+    public static final class WrapVec2 implements Function { public void run(TomVM vm){
 
         float[] vec2 = new float[]{ vm.getRealParam(2), vm.getRealParam(1) };
         vm.getReg().setIntVal ( Data.fillTempRealArray(vm.getData(), vm.getDataTypes(), 2, vec2));
     }
     }
-    public final class WrapMatrixZero implements Function { public void run(TomVM vm){
+    public static final class WrapMatrixZero implements Function { public void run(TomVM vm){
 
         ClearMatrix ();
```
Comment (NateIsStalling) [inline library/src/main/java/com/basic4gl/library/standard/TrigBasicLib.java:534]: cleanup method naming conventions in TrigBasicLib
